Add some ICEs
rust-lang/glacier pull request #857
Opened 2021-07-04 22:55 UTC by fanninpm

- Add 86528
- Add 86535
- Add 86642
- Add 86703
- Add 86719
- Add 86720
- Add 86756
- Add 86784
- Add 86800
- Add 86820
- Add 86850

2021-07-06 00:21 UTC, JohnTitor requested changes
Some examples need to be tweaked manually. Let me do and push it.

2021-07-06 00:21 UTC, JohnTitor commented on ices/86535.rs
> +}
```suggestion
#![feature(box_syntax)]
fn main() {
    let _: Box<[isize]> = box { loop {} };
}
```

2021-07-06 00:21 UTC, JohnTitor commented on ices/86642.rs
> +#![feature(impl_trait_in_bindings)]
It seems like that this is likely a duplicate of the mentioned issue but let's see it with glacier.

2021-07-06 00:21 UTC, JohnTitor commented on ices/86800.rs
> +}
```suggestion
#![feature(min_type_alias_impl_trait)]
use std::future::Future;

struct Connection {}

trait Transaction {}

struct TestTransaction<'conn> {
    conn: &'conn Connection,
}

impl<'conn> Transaction for TestTransaction<'conn> {}

struct Context {}

type TransactionResult<O> = Result<O, ()>;

type TransactionFuture<'__, O> = impl '__ + Future<Output = TransactionResult<O>>;

fn execute_transaction_fut<'f, F, O>(
    f: F,
) -> impl FnOnce(&mut dyn Transaction) -> TransactionFuture<O>
where
    F: FnOnce(&mut dyn Transaction) -> TransactionFuture<O> + 'f,
{
    f
}

impl Context {
    async fn do_transaction<O>(
        &self,
        f: impl FnOnce(&mut dyn Transaction) -> TransactionFuture<O>,
    ) -> TransactionResult<O> {
        let mut conn = Connection {};
        let mut transaction = TestTransaction { conn: &mut conn };
        f(&mut transaction).await
    }
}

```

2021-07-06 00:21 UTC, JohnTitor commented on ices/86820.sh
> +#!/bin/bash
This doesn't have to be run as an actual crate. All it needs is to place `assert!` on `fn main()`.

2021-07-06 00:42 UTC, JohnTitor commented
I'm a bit concerned that one example is very large but it doesn't affect the check time much, so I'm going to accept it.

2021-07-06 00:42 UTC, merged

2021-07-07 15:07 UTC, hellow554 commented
@JohnTitor you mean https://github.com/rust-lang/rust/issues/86784#issuecomment-872886518 ?

Yeah, it's crazy how big it is, but surprisingly fast to compile, mostly because it's only assignments. Thanks for adding it ;)